"""added clusters (files) to Repo

Revision ID: 237edb79a826
Revises: 56b64e8ac64d
Create Date: 2024-10-04 11:28:04.647215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237edb79a826'
down_revision: Union[str, None] = '56b64e8ac64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('cluster_files', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'cluster_files')
    # ### end Alembic commands ###
