"""added owner field to Repo

Revision ID: a739fc5f962f
Revises: b5dbec62f380
Create Date: 2024-09-18 16:14:17.193474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a739fc5f962f'
down_revision: Union[str, None] = 'b5dbec62f380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'owner')
    # ### end Alembic commands ###
