"""added graph_path and summary_path

Revision ID: cd6d4820e16b
Revises: 839d8d4452de
Create Date: 2024-09-19 15:04:40.287235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd6d4820e16b"
down_revision: Union[str, None] = "839d8d4452de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repos", sa.Column("graph_path", sa.String(), nullable=True))
    op.add_column("repos", sa.Column("summary_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repos", "summary_path")
    op.drop_column("repos", "graph_path")
    # ### end Alembic commands ###
