"""refactored user and repo models

Revision ID: da95aeecb8f1
Revises: 02a7f45559cf
Create Date: 2024-08-22 15:19:51.032770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da95aeecb8f1'
down_revision: Union[str, None] = '02a7f45559cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('repo_config')
    op.add_column('user', sa.Column('repo_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'repos', ['repo_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'repo_user_id')
    op.create_table('repo_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('main', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='repo_config_pkey')
    )
    op.drop_table('repos')
    # ### end Alembic commands ###
